name: LSChat
version: 1.0-SNAPSHOT
main: me.miyeoukman.lschat.Main
api-version: 1.20
description: LSChat plugin for Chzzk and YouTube integration.
author: miyeoukman
commands:
  lschat:
    description: Main command for LSChat
    usage: /lschat [toggle|reload|test|testdonate]
    permission: lschat.use
    permission-message: You do not have permission to use this command.

permissions:
  lschat.use:
    description: Allows usage of /lschat toggle
    default: true
  lschat.admin:
    description: Allows usage of admin commands like reload and test
    default: op
